### ISSUE TITLE
How to run this repository in linux?

### ISSUE THREAD

**Issue by sciart17** [hmmlillian/Gray-Image-Retrieval#6]
Hello, thanks for your outstanding work!
I am trying to follow this repo to get image inference used in DeepExemplar. I have uploaded dataset and pretrained model to remote server but I encountered the problem that the process failed in linux. I wonder which part of module I could change or recompile to make the repo run in linux successfully?
Thanks again for your attention!

`Traceback (most recent call last):
  File "/home/***/code/Gray-Image-Retrieval/test.py", line 1, in <module>
    import _init_paths
  File "/home/***/code/Gray-Image-Retrieval/_init_paths.py", line 25, in <module>
    search_dll = windll.LoadLibrary('Search.dll')
NameError: name 'windll' is not defined`

**Comment by hmmlillian** [comment]
@sciart17 Because the source code for searching was written in C++ and compiled to a Windows dynamic library using Visual Studio compiler. That's the reason why it cannot be directly run on Linux. Some modification is necessary if this code is moved to Linux. Please contact me via email if you have more questions.

**Comment by sciart17** [comment]
I tried to use some modules like [zugbruecke](https://github.com/pleiszenburg/zugbruecke) to load DLLs but failed. Now I have successfully run the preogram on a computer whose system is Windows10. Thanks for your reply!
